# Generated by Django 3.2.16 on 2022-12-02 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_complaint_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInOutTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
