# Generated by Django 3.2.16 on 2022-12-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_studentinouttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinouttime',
            name='in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studentinouttime',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
