# Generated by Django 3.2.16 on 2022-12-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20221203_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
